version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: task-management-db
    restart: always
    environment:
      MYSQL_DATABASE: task_management_db
      MYSQL_ROOT_PASSWORD: Qwertyuiop
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: task-management-app
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/task_management_db?ServerTimezone=UTC&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Qwertyuiop
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

volumes:
  mysql_data:
